services:
  reranker:
    image: ghcr.io/huggingface/text-embeddings-inference:1.8
    container_name: podcast-reranker
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./reranker-models:/data
    command: --model-id BAAI/bge-reranker-large
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s